### ISSUE TITLE
where is zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

### ISSUE THREAD

**Issue by moboard** [AnTuanHa/dotfiles#1]
1.  ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
   where is this?

**Comment by AnTuanHa** [comment]
https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md

Create a .zsh folder and then git clone zsh-syntax-highlighting.
